import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from 'next-auth/react';
import Provider from "../../context/Provider";
import "./globals.css";
import Header from "@/lib/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider session>
        <body className={inter.className}>
          <Header></Header>
          {children}
        </body>
      </Provider>
    </html>
  );
}
